// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/spf13/viper"
	"server_go/internal/handler"
	"server_go/internal/repository"
	"server_go/internal/server"
	"server_go/internal/service"
	"server_go/pkg/log"
)

// Injectors from wire.go:

func newApp(viperViper *viper.Viper, logger *log.Logger) (*gin.Engine, func(), error) {
	handlerHandler := handler.NewHandler(logger)
	serviceService := service.NewService(logger)
	db := repository.NewBaseDb(viperViper, logger)
	baseRepository := repository.NewBaseRepository(logger, db)
	userRepository := repository.NewUserRepository(baseRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	adminRepository := repository.NewAdminRepository(baseRepository)
	adminService := service.NewAdminService(serviceService, adminRepository)
	adminHandler := handler.NewAdminHandler(handlerHandler, adminService)
	courseRepository := repository.NewCourseRepository(baseRepository)
	courseService := service.NewCourseService(serviceService, courseRepository)
	courseHandler := handler.NewCourseHandler(handlerHandler, courseService)
	resourceCategoryRepository := repository.NewResourceCategoryRepository(baseRepository)
	resourceCategoryService := service.NewResourceCategoryService(serviceService, resourceCategoryRepository)
	resourceCategoryHandler := handler.NewResourceCategoryHandler(handlerHandler, resourceCategoryService)
	schoolRepository := repository.NewSchoolRepository(baseRepository)
	schoolService := service.NewSchoolService(serviceService, schoolRepository)
	schoolHandler := handler.NewSchoolHandler(handlerHandler, schoolService)
	courseCategoryRepository := repository.NewCourseCategoryRepository(baseRepository)
	courseCategoryService := service.NewCourseCategoryService(serviceService, courseCategoryRepository)
	courseCategoryHandler := handler.NewCourseCategoryHandler(handlerHandler, courseCategoryService)
	chapterRepository := repository.NewChapterRepository(baseRepository)
	chapterService := service.NewChapterService(serviceService, chapterRepository)
	chapterHandler := handler.NewChapterHandler(handlerHandler, chapterService)
	sectionRepository := repository.NewSectionRepository(baseRepository)
	sectionService := service.NewSectionService(serviceService, sectionRepository)
	sectionHandler := handler.NewSectionHandler(handlerHandler, sectionService)
	commentRepository := repository.NewCommentRepository(baseRepository)
	commentService := service.NewCommentService(serviceService, commentRepository)
	commentHandler := handler.NewCommentHandler(handlerHandler, commentService)
	resourceRepository := repository.NewResourceRepository(baseRepository)
	resourceService := service.NewResourceService(serviceService, resourceRepository)
	resourceHandler := handler.NewResourceHandler(handlerHandler, resourceService)
	giveScoreRepository := repository.NewGiveScoreRepository(baseRepository)
	giveScoreService := service.NewGiveScoreService(serviceService, giveScoreRepository)
	giveScoreHandler := handler.NewgiveScoreHandler(handlerHandler, giveScoreService)
	giveScoreThemeRepository := repository.NewGiveScoreThemeRepository(baseRepository)
	giveScoreThemeService := service.NewGiveScoreThemeService(serviceService, giveScoreThemeRepository)
	giveScoreThemeHandler := handler.NewgiveScoreThemeHandler(handlerHandler, giveScoreThemeService)
	giveScoreCategoryRepository := repository.NewGiveScoreCategoryRepository(baseRepository)
	giveScoreCategoryService := service.NewGiveScoreCategoryService(serviceService, giveScoreCategoryRepository)
	giveScoreCategoryHandler := handler.NewgiveScoreCategoryHandler(handlerHandler, giveScoreCategoryService)
	accountRepository := repository.NewAccountRepository(baseRepository)
	accountService := service.NewAccountService(serviceService, accountRepository)
	accountHandler := handler.NewAccountHandler(handlerHandler, accountService)
	studentUserRepository := repository.NewStudentUserRepository(baseRepository)
	studentUserService := service.NewStudentUserService(serviceService, studentUserRepository)
	studentUserHandler := handler.NewStudentUserHandler(handlerHandler, studentUserService)
	engine := server.NewServerHTTP(logger, userHandler, adminHandler, courseHandler, resourceCategoryHandler, schoolHandler, courseCategoryHandler, chapterHandler, sectionHandler, commentHandler, resourceHandler, giveScoreHandler, giveScoreThemeHandler, giveScoreCategoryHandler, accountHandler, studentUserHandler)
	return engine, func() {
	}, nil
}

// wire.go:

var ServerSet = wire.NewSet(server.NewServerHTTP)

var RepositorySet = wire.NewSet(repository.NewBaseDb, repository.NewBaseRepository, repository.NewUserRepository, repository.NewAdminRepository, repository.NewCourseRepository, repository.NewResourceCategoryRepository, repository.NewSchoolRepository, repository.NewCourseCategoryRepository, repository.NewChapterRepository, repository.NewSectionRepository, repository.NewCommentRepository, repository.NewResourceRepository, repository.NewGiveScoreRepository, repository.NewGiveScoreThemeRepository, repository.NewGiveScoreCategoryRepository, repository.NewAccountRepository, repository.NewStudentUserRepository)

var ServiceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewAdminService, service.NewCourseService, service.NewResourceCategoryService, service.NewSchoolService, service.NewCourseCategoryService, service.NewChapterService, service.NewSectionService, service.NewCommentService, service.NewResourceService, service.NewGiveScoreService, service.NewGiveScoreThemeService, service.NewGiveScoreCategoryService, service.NewAccountService, service.NewStudentUserService)

var HandlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewAdminHandler, handler.NewCourseHandler, handler.NewResourceCategoryHandler, handler.NewSchoolHandler, handler.NewCourseCategoryHandler, handler.NewChapterHandler, handler.NewSectionHandler, handler.NewCommentHandler, handler.NewResourceHandler, handler.NewgiveScoreHandler, handler.NewgiveScoreThemeHandler, handler.NewgiveScoreCategoryHandler, handler.NewAccountHandler, handler.NewStudentUserHandler)
