// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"ai_summary_project/internal/handler"
	"ai_summary_project/internal/repository"
	"ai_summary_project/internal/server"
	"ai_summary_project/internal/service"
	"ai_summary_project/pkg/app"
	"ai_summary_project/pkg/jwt"
	"ai_summary_project/pkg/log"
	"ai_summary_project/pkg/server/http"
	"ai_summary_project/pkg/sid"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

// Wire 入口
func NewWire(v *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(v, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	jwtJWT := jwt.NewJwt(v)
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	courseRepository := repository.NewCourseRepository(repositoryRepository)
	bookRepository := repository.NewBookRepository(repositoryRepository)
	courseService := service.NewCourseService(serviceService, courseRepository, bookRepository)
	courseHandler := handler.NewCourseHandler(handlerHandler, courseService)
	usersRepository := repository.NewUsersRepository(repositoryRepository)
	usersService := service.NewUsersService(serviceService, usersRepository)
	usersHandler := handler.NewUsersHandler(handlerHandler, usersService)
	httpServer := server.NewHTTPServer(logger, v, courseHandler, usersHandler)
	appApp := newApp(httpServer)
	return appApp, func() {
	}, nil
}

// wire.go:

// 提取依赖集合
var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewCourseRepository, repository.NewBookRepository, repository.NewUsersRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewCourseService, service.NewUsersService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewCourseHandler, handler.NewUsersHandler)

var serverSet = wire.NewSet(server.NewHTTPServer)

// 应用入口构建
func newApp(httpServer *http.Server) *app.App {
	return app.NewApp(app.WithServer(httpServer), app.WithName("course-server"))
}
